# arxivの学問領域の指定
subject: 'cat:cs.CV OR cat:cs.GR OR cat:cs.HC'

# 検索キーワード
keywords:
        animation: 1
        animations: 1
        animated: 1
        articulated: 1
        avatar: 1
        avatars: 1
        cloud: 1
        compression: 1
        decomposition: 1
        deformable: 1
        deformation: 1
        differentiable: 1
        dynamics: 1
        fabrication: 1
        frequency: 1
        geometric: 1
        geometry: 1
        grid: 1
        haptic: 1
        illumination: 1
        implicit: 1
        inverse: 1
        irradiance: 1
        koopman: 1
        laplace-beltrami: 2
        laplacian: 1
        laplacians: 1
        material: 2
        materials: 2
        marching cube: 2
        marching cubes: 2
        mesh: 2
        meshing: 1
        microfacet: 1
        multigrid: 1
        multi-grid: 1
        multiview: 2
        multi-view: 2
        nerf: 2
        pbr: 1
        photogrammetry: 1
        photometric: 1
        photometry: 1
        photon: 1
        point: 1
        polygon: 1
        radiance: 1
        radiosity: 1
        rasterization: 1
        rasterizer: 1
        ray tracing: 2
        ray tracer: 2
        remeshing: 1
        renderer: 1
        rendering: 1
        rotation: 1
        sdf: 2
        shader: 1
        shading: 1
        skinning: 1
        spectral: 1
        specular: 1
        spherical: 1
        subdivision: 1
        surface: 1
        surfaces: 1
        texture: 1
        texturing: 1
        triangulation: 1
        triangulations: 1
        view synthesis: 2
        volume: 1
        volumetric: 1
        

# 通知の閾値
score_threshold: 0
