# arxivの学問領域の指定
subject: 'cat:cs.GR OR cat:cs.CV OR cat:cs.HC'

# 検索キーワード
keywords:
        aerial image: -2
        Alzheimer: -2
        animation: 1
        animated: 1
        articulated: 1
        automotive: -1
        autonomous driving: -2
        avatar: 1
        bobsled: -1
        brain: -1
        CAD: 1
        cardiac: -2
        choroid plexus: -2
        cloud: 1
        cloth: 2
        chromosome: -2
        compression: 3
        contact: 1
        cosmic: -1
        COVID-19: -2
        CT: -2
        curvature: 1
        decomposition: 2
        deepfake: -1
        deep learning: -1
        deformable: 1
        deformation: 3
        dynamics: 1
        EMG: -1
        fabrication: 1
        FEM: 1
        FLIP: 1
        fluid: 1
        frequency: 1
        fungi: -1
        garment: 1
        geometric: 1
        geometry: 2
        graph: 1
        grid: 1
        histopathology: -2
        hydrodynamics: 1
        illumination: 1
        implicit: 1
        interreflection: 1
        inverse: 1
        irradiance: 1
        koopman: 2
        laplace-beltrami: 3
        laplacian: 1
        level set: 1
        liver: -1
        lung: -1
        material: 1
        material point method: 3
        marching cubes: 2
        mesh: 2
        microfacet: 1
        model reduction: 2
        monte carlo: 1
        MRI: -2
        multigrid: 1
        multi-grid: 1
        multiview: 2
        multi-view: 2
        nerf: 2
        neurosurgery: -1
        object detection: -1
        object estimation: -1
        octree: 1
        particle: 1
        particle-in-cell: 2
        pbr: 1
        photogrammetry: 1
        photometric: 1
        photometry: 1
        photon: 1
        physics: 1
        point: 1
        positional encoding: 2
        polygon: 1
        projective dynamics: 2
        pulmonary fibrosis: -2
        radiance: 1
        radiosity: 1
        rasterization: 1
        rasterizer: 1
        ray tracing: 2
        ray tracer: 2
        remeshing: 2
        renderer: 1
        rendering: 1
        rigging: 1
        rotation: 1
        sdf: 2
        shader: 1
        shading: 1
        signed distance field: 2
        simulation: 1
        skinning: 2
        smart: -1
        spectral: 1
        specular: 1
        spherical: 1
        subdivision: 1
        surface: 1
        surgical: -1
        tactile: 1
        telepresence: -1
        texture: 1
        triangulation: 1
        triangulations: 1
        TV transform: 2
        upsampling: 1
        vehicle: -1
        view synthesis: 2
        volume: 1
        volumetric: 1
        voxel: 2
        winding number: 2
        

# 通知の閾値
score_threshold: 2.0
